// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.0--rc2
// source: notif.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FruitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *FruitRequest) Reset() {
	*x = FruitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notif_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FruitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FruitRequest) ProtoMessage() {}

func (x *FruitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notif_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FruitRequest.ProtoReflect.Descriptor instead.
func (*FruitRequest) Descriptor() ([]byte, []int) {
	return file_notif_proto_rawDescGZIP(), []int{0}
}

func (x *FruitRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PoetryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Linecount int32 `protobuf:"varint,1,opt,name=linecount,proto3" json:"linecount,omitempty"`
}

func (x *PoetryRequest) Reset() {
	*x = PoetryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notif_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoetryRequest) ProtoMessage() {}

func (x *PoetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notif_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoetryRequest.ProtoReflect.Descriptor instead.
func (*PoetryRequest) Descriptor() ([]byte, []int) {
	return file_notif_proto_rawDescGZIP(), []int{1}
}

func (x *PoetryRequest) GetLinecount() int32 {
	if x != nil {
		return x.Linecount
	}
	return 0
}

type NutritionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Calories      float32 `protobuf:"fixed32,1,opt,name=calories,proto3" json:"calories,omitempty"`
	Fat           float32 `protobuf:"fixed32,2,opt,name=fat,proto3" json:"fat,omitempty"`
	Sugar         float32 `protobuf:"fixed32,3,opt,name=sugar,proto3" json:"sugar,omitempty"`
	Carbohydrates float32 `protobuf:"fixed32,4,opt,name=carbohydrates,proto3" json:"carbohydrates,omitempty"`
	Protein       float32 `protobuf:"fixed32,5,opt,name=protein,proto3" json:"protein,omitempty"`
}

func (x *NutritionInfo) Reset() {
	*x = NutritionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notif_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NutritionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NutritionInfo) ProtoMessage() {}

func (x *NutritionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_notif_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NutritionInfo.ProtoReflect.Descriptor instead.
func (*NutritionInfo) Descriptor() ([]byte, []int) {
	return file_notif_proto_rawDescGZIP(), []int{2}
}

func (x *NutritionInfo) GetCalories() float32 {
	if x != nil {
		return x.Calories
	}
	return 0
}

func (x *NutritionInfo) GetFat() float32 {
	if x != nil {
		return x.Fat
	}
	return 0
}

func (x *NutritionInfo) GetSugar() float32 {
	if x != nil {
		return x.Sugar
	}
	return 0
}

func (x *NutritionInfo) GetCarbohydrates() float32 {
	if x != nil {
		return x.Carbohydrates
	}
	return 0
}

func (x *NutritionInfo) GetProtein() float32 {
	if x != nil {
		return x.Protein
	}
	return 0
}

type FruitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id         int32          `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Family     string         `protobuf:"bytes,3,opt,name=family,proto3" json:"family,omitempty"`
	Order      string         `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`
	Genus      string         `protobuf:"bytes,5,opt,name=genus,proto3" json:"genus,omitempty"`
	Nutritions *NutritionInfo `protobuf:"bytes,6,opt,name=nutritions,proto3" json:"nutritions,omitempty"`
}

func (x *FruitResponse) Reset() {
	*x = FruitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notif_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FruitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FruitResponse) ProtoMessage() {}

func (x *FruitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notif_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FruitResponse.ProtoReflect.Descriptor instead.
func (*FruitResponse) Descriptor() ([]byte, []int) {
	return file_notif_proto_rawDescGZIP(), []int{3}
}

func (x *FruitResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FruitResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FruitResponse) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *FruitResponse) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *FruitResponse) GetGenus() string {
	if x != nil {
		return x.Genus
	}
	return ""
}

func (x *FruitResponse) GetNutritions() *NutritionInfo {
	if x != nil {
		return x.Nutritions
	}
	return nil
}

type PoetryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title     string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author    string   `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Lines     []string `protobuf:"bytes,3,rep,name=lines,proto3" json:"lines,omitempty"`
	Linecount string   `protobuf:"bytes,4,opt,name=linecount,proto3" json:"linecount,omitempty"`
}

func (x *PoetryResponse) Reset() {
	*x = PoetryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notif_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoetryResponse) ProtoMessage() {}

func (x *PoetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notif_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoetryResponse.ProtoReflect.Descriptor instead.
func (*PoetryResponse) Descriptor() ([]byte, []int) {
	return file_notif_proto_rawDescGZIP(), []int{4}
}

func (x *PoetryResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PoetryResponse) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PoetryResponse) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *PoetryResponse) GetLinecount() string {
	if x != nil {
		return x.Linecount
	}
	return ""
}

var File_notif_proto protoreflect.FileDescriptor

var file_notif_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x22, 0x22, 0x0a, 0x0c, 0x46, 0x72, 0x75, 0x69, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2d, 0x0a, 0x0d, 0x50, 0x6f, 0x65, 0x74,
	0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x69, 0x6e,
	0x65, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6c, 0x69,
	0x6e, 0x65, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x93, 0x01, 0x0a, 0x0d, 0x4e, 0x75, 0x74, 0x72,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c,
	0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x63, 0x61, 0x6c,
	0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x03, 0x66, 0x61, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x75, 0x67, 0x61, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x75, 0x67, 0x61, 0x72, 0x12, 0x24, 0x0a,
	0x0d, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x68, 0x79, 0x64, 0x72, 0x61, 0x74, 0x65, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x0d, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x68, 0x79, 0x64, 0x72, 0x61,
	0x74, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x69, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x69, 0x6e, 0x22, 0xad, 0x01,
	0x0a, 0x0d, 0x46, 0x72, 0x75, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x65, 0x6e, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x67, 0x65, 0x6e, 0x75, 0x73, 0x12, 0x34, 0x0a, 0x0a, 0x6e, 0x75, 0x74, 0x72, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6e, 0x6f,
	0x74, 0x69, 0x66, 0x2e, 0x4e, 0x75, 0x74, 0x72, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x0a, 0x6e, 0x75, 0x74, 0x72, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x72, 0x0a,
	0x0e, 0x50, 0x6f, 0x65, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x69,
	0x6e, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x69, 0x6e, 0x65, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x69, 0x6e, 0x65, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x32, 0x8b, 0x01, 0x0a, 0x0c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x46, 0x72, 0x75, 0x69, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x13, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x2e, 0x46, 0x72, 0x75, 0x69, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x2e,
	0x46, 0x72, 0x75, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12,
	0x3e, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x65, 0x74, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x14, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x2e, 0x50, 0x6f, 0x65, 0x74, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x2e, 0x50,
	0x6f, 0x65, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42,
	0x0a, 0x5a, 0x08, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_notif_proto_rawDescOnce sync.Once
	file_notif_proto_rawDescData = file_notif_proto_rawDesc
)

func file_notif_proto_rawDescGZIP() []byte {
	file_notif_proto_rawDescOnce.Do(func() {
		file_notif_proto_rawDescData = protoimpl.X.CompressGZIP(file_notif_proto_rawDescData)
	})
	return file_notif_proto_rawDescData
}

var file_notif_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_notif_proto_goTypes = []interface{}{
	(*FruitRequest)(nil),   // 0: notif.FruitRequest
	(*PoetryRequest)(nil),  // 1: notif.PoetryRequest
	(*NutritionInfo)(nil),  // 2: notif.NutritionInfo
	(*FruitResponse)(nil),  // 3: notif.FruitResponse
	(*PoetryResponse)(nil), // 4: notif.PoetryResponse
}
var file_notif_proto_depIdxs = []int32{
	2, // 0: notif.FruitResponse.nutritions:type_name -> notif.NutritionInfo
	0, // 1: notif.NotifService.GetFruitInfo:input_type -> notif.FruitRequest
	1, // 2: notif.NotifService.GetPoetryInfo:input_type -> notif.PoetryRequest
	3, // 3: notif.NotifService.GetFruitInfo:output_type -> notif.FruitResponse
	4, // 4: notif.NotifService.GetPoetryInfo:output_type -> notif.PoetryResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_notif_proto_init() }
func file_notif_proto_init() {
	if File_notif_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_notif_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FruitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notif_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoetryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notif_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NutritionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notif_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FruitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notif_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoetryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_notif_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notif_proto_goTypes,
		DependencyIndexes: file_notif_proto_depIdxs,
		MessageInfos:      file_notif_proto_msgTypes,
	}.Build()
	File_notif_proto = out.File
	file_notif_proto_rawDesc = nil
	file_notif_proto_goTypes = nil
	file_notif_proto_depIdxs = nil
}
