# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notif.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bnotif.proto\x12\x05notif\"\x1c\n\x0c\x46ruitRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\"\n\rPoetryRequest\x12\x11\n\tlinecount\x18\x01 \x01(\x05\"e\n\rNutritionInfo\x12\x10\n\x08\x63\x61lories\x18\x01 \x01(\x02\x12\x0b\n\x03\x66\x61t\x18\x02 \x01(\x02\x12\r\n\x05sugar\x18\x03 \x01(\x02\x12\x15\n\rcarbohydrates\x18\x04 \x01(\x02\x12\x0f\n\x07protein\x18\x05 \x01(\x02\"\x81\x01\n\rFruitResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x0e\n\x06\x66\x61mily\x18\x03 \x01(\t\x12\r\n\x05order\x18\x04 \x01(\t\x12\r\n\x05genus\x18\x05 \x01(\t\x12(\n\nnutritions\x18\x06 \x01(\x0b\x32\x14.notif.NutritionInfo\"Q\n\x0ePoetryResponse\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\r\n\x05lines\x18\x03 \x03(\t\x12\x11\n\tlinecount\x18\x04 \x01(\t2\x8b\x01\n\x0cNotifService\x12;\n\x0cGetFruitInfo\x12\x13.notif.FruitRequest\x1a\x14.notif.FruitResponse0\x01\x12>\n\rGetPoetryInfo\x12\x14.notif.PoetryRequest\x1a\x15.notif.PoetryResponse0\x01\x42\nZ\x08../protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notif_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\010../proto'
  _globals['_FRUITREQUEST']._serialized_start=22
  _globals['_FRUITREQUEST']._serialized_end=50
  _globals['_POETRYREQUEST']._serialized_start=52
  _globals['_POETRYREQUEST']._serialized_end=86
  _globals['_NUTRITIONINFO']._serialized_start=88
  _globals['_NUTRITIONINFO']._serialized_end=189
  _globals['_FRUITRESPONSE']._serialized_start=192
  _globals['_FRUITRESPONSE']._serialized_end=321
  _globals['_POETRYRESPONSE']._serialized_start=323
  _globals['_POETRYRESPONSE']._serialized_end=404
  _globals['_NOTIFSERVICE']._serialized_start=407
  _globals['_NOTIFSERVICE']._serialized_end=546
# @@protoc_insertion_point(module_scope)
