# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import notif_pb2 as notif__pb2


class NotifServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFruitInfo = channel.unary_stream(
                '/notif.NotifService/GetFruitInfo',
                request_serializer=notif__pb2.FruitRequest.SerializeToString,
                response_deserializer=notif__pb2.FruitResponse.FromString,
                )
        self.GetPoetryInfo = channel.unary_stream(
                '/notif.NotifService/GetPoetryInfo',
                request_serializer=notif__pb2.PoetryRequest.SerializeToString,
                response_deserializer=notif__pb2.PoetryResponse.FromString,
                )


class NotifServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetFruitInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPoetryInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotifServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFruitInfo': grpc.unary_stream_rpc_method_handler(
                    servicer.GetFruitInfo,
                    request_deserializer=notif__pb2.FruitRequest.FromString,
                    response_serializer=notif__pb2.FruitResponse.SerializeToString,
            ),
            'GetPoetryInfo': grpc.unary_stream_rpc_method_handler(
                    servicer.GetPoetryInfo,
                    request_deserializer=notif__pb2.PoetryRequest.FromString,
                    response_serializer=notif__pb2.PoetryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'notif.NotifService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NotifService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFruitInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/notif.NotifService/GetFruitInfo',
            notif__pb2.FruitRequest.SerializeToString,
            notif__pb2.FruitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPoetryInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/notif.NotifService/GetPoetryInfo',
            notif__pb2.PoetryRequest.SerializeToString,
            notif__pb2.PoetryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
